import type { Metadata } from 'next';
import { locales, defaultLocale, type Locale } from '@/i18n/routing';

/**
 * Resolves the canonical base URL. Falls back to localhost for dev so the
 * site still renders, but in prod NEXT_PUBLIC_SITE_URL must be set.
 */
export const siteUrl = (
  process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000'
).replace(/\/$/, '');

/**
 * Build the public path for a locale + relative path.
 * The site uses `localePrefix: 'as-needed'` — `en` has no prefix.
 */
export function localePath(locale: Locale, path: string = ''): string {
  const clean = path.startsWith('/') ? path : path ? `/${path}` : '';
  if (locale === defaultLocale) return clean || '/';
  return `/${locale}${clean}`;
}

export function absoluteUrl(locale: Locale, path: string = ''): string {
  return `${siteUrl}${localePath(locale, path)}`;
}

/**
 * Build the `alternates` object for Next.js Metadata — canonical URL plus
 * `hreflang` entries for every locale, with `x-default` pointing at the
 * default locale. This is the single most-impactful multilingual SEO fix.
 */
export function buildAlternates(
  currentLocale: Locale,
  path: string = '',
): NonNullable<Metadata['alternates']> {
  const languages: Record<string, string> = {};
  for (const loc of locales) {
    languages[loc] = absoluteUrl(loc, path);
  }
  languages['x-default'] = absoluteUrl(defaultLocale, path);
  return {
    canonical: absoluteUrl(currentLocale, path),
    languages,
  };
}

/**
 * Map our locale codes to OpenGraph locale codes (BCP-47).
 */
const OG_LOCALES: Record<Locale, string> = {
  en: 'en_US',
  ru: 'ru_RU',
  uk: 'uk_UA',
  ka: 'ka_GE',
  fr: 'fr_FR',
  de: 'de_DE',
  es: 'es_ES',
  ar: 'ar_AR',
  ur: 'ur_PK',
  hi: 'hi_IN',
};

export function ogLocale(locale: Locale): string {
  return OG_LOCALES[locale] || 'en_US';
}

export function ogLocaleAlternates(currentLocale: Locale): string[] {
  return locales
    .filter((l) => l !== currentLocale)
    .map((l) => OG_LOCALES[l]);
}

/**
 * Default social-card image. Points at the app-root `opengraph-image` route
 * (generated by next/og). Relative URL — Next resolves it against
 * `metadataBase`. Attach to every page's `openGraph.images` / `twitter.images`
 * because a route that defines its own `openGraph` does NOT inherit the
 * file-based image. width/height/type complete the OG tag set Ahrefs checks.
 */
export const OG_IMAGE = {
  url: '/opengraph-image',
  width: 1200,
  height: 630,
  alt: 'The NATRO File — a documented case in reputation pricing',
} as const;

/**
 * Image licensing — the author who holds copyright over the case-file imagery
 * and the page describing reuse terms. Surfaced in every `ImageObject` so
 * Google can show the "Licensable" badge in Google Images and satisfies the
 * `creator` / `copyrightNotice` / `license` / `acquireLicensePage` fields the
 * Search Console "Image metadata" report asks for.
 */
export const IMAGE_AUTHOR = 'Yevgeniy Moykin';
export const IMAGE_LICENSE_PATH = '/image-license';
export const IMAGE_COPYRIGHT_YEAR = 2026;

/** Absolute URL of the human-readable license/usage-terms page. */
export function imageLicenseUrl(): string {
  return `${siteUrl}${IMAGE_LICENSE_PATH}`;
}

/**
 * Attribution string a re-user must display. Combines the required author
 * credit (Yevgeniy Moykin) with the primary source the image was captured
 * from, so the license's "cite the source" requirement is machine-readable.
 */
export function imageCreditText(source?: string): string {
  const base = `© ${IMAGE_COPYRIGHT_YEAR} ${IMAGE_AUTHOR} · natro.meme`;
  return source ? `${base} — source: ${source}` : base;
}

/**
 * The licensing block to spread into an `ImageObject`. Every field Google's
 * image-metadata report flags as missing is filled here. Reuse is allowed
 * only with visible credit to the author AND a link back to the source page.
 */
export function imageLicenseFields(source?: string) {
  const license = imageLicenseUrl();
  return {
    creator: { '@type': 'Person', name: IMAGE_AUTHOR },
    copyrightHolder: { '@type': 'Person', name: IMAGE_AUTHOR },
    copyrightYear: IMAGE_COPYRIGHT_YEAR,
    copyrightNotice: `© ${IMAGE_COPYRIGHT_YEAR} ${IMAGE_AUTHOR}. Reuse requires visible credit to ${IMAGE_AUTHOR} and a link back to the source page on natro.meme.`,
    creditText: imageCreditText(source),
    license,
    acquireLicensePage: license,
  } as const;
}

/**
 * Trim a `<meta name="description">` to a length search engines actually
 * render (~155 chars), cutting on a word boundary and appending an ellipsis.
 * No-op when already short, so it is safe to wrap every page's description.
 */
export function clampDescription(text: string | undefined, max = 155): string {
  const s = (text || '').trim().replace(/\s+/g, ' ');
  if (s.length <= max) return s;
  const cut = s.slice(0, max);
  const lastSpace = cut.lastIndexOf(' ');
  const body = lastSpace > max * 0.6 ? cut.slice(0, lastSpace) : cut;
  return body.replace(/[\s.,;:—-]+$/, '') + '…';
}

/**
 * Keep a `<title>` under ~60 chars. First drops the trailing brand segment
 * after the last separator (" — ", " | ", " · "); only if that still doesn't
 * fit does it hard-truncate. No-op when already short.
 */
export function clampTitle(text: string, max = 60): string {
  const s = (text || '').trim().replace(/\s+/g, ' ');
  if (s.length <= max) return s;
  let sep = -1;
  for (const token of [' — ', ' | ', ' · ', ' - ']) {
    sep = Math.max(sep, s.lastIndexOf(token));
  }
  if (sep > 0 && sep <= max) return s.slice(0, sep);
  const cut = s.slice(0, max - 1);
  const lastSpace = cut.lastIndexOf(' ');
  const body = lastSpace > max * 0.5 ? cut.slice(0, lastSpace) : cut;
  return body.replace(/[\s|·—-]+$/, '') + '…';
}
